package org.key_project.tptp2key;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Turns a collected TPTP problem into the text of a .key problem file.
 *
 * The direction of the translation follows from what each side asks. A TPTP problem asks whether
 * its conjecture follows from its axioms, which is what a KeY sequent asks, so the two line up
 * without a detour: the axioms become the antecedent and the conjecture the succedent. A closed
 * proof then means the problem is a Theorem. CNF problems have no conjecture, only clauses whose
 * satisfiability is in question, and there the sequent is {@code clauses ==> false}, which is valid
 * exactly when the clause set is unsatisfiable.
 *
 * Unlike SMT-LIB, TPTP keeps formulas and terms apart in the same way KeY does, so nothing has to
 * be bridged between the two. What does need care is that untyped TPTP has one universe, which
 * becomes one sort here, while TFF's {@code $int} is KeY's own {@code int} with all its rules.
 */
public final class Translator {

    /** The sort standing for TPTP's universe of individuals, {@code $i}. */
    private static final String INDIVIDUAL = Names.SORT + "i";

    /** A quantified variable: the name it prints as, and the type it was quantified at. */
    private record Bound(String name, Ast.Type type) {}

    private final Collector collector;
    private final Map<String, Ast.Signature> signatures;
    private final Names names = new Names();
    private final Set<String> sorts = new LinkedHashSet<>();
    private final Map<String, String> funDecls = new LinkedHashMap<>();
    private final Map<String, String> predDecls = new LinkedHashMap<>();
    private final Map<String, String> uniqueDecls = new LinkedHashMap<>();
    private final boolean numbersAreIntegers;

    public Translator(Collector collector) {
        this.collector = collector;
        this.signatures = Signatures.complete(collector.inputs(), collector.signatures());
        // Untyped TPTP has no arithmetic, so a numeral there is an individual like any other.
        this.numbersAreIntegers = collector.language() == Collector.Language.TFF;
    }

    /** The complete text of the .key file, leaving KeY its own strategy settings. */
    public String run(String sourceName, String status) {
        return run(sourceName, status, null);
    }

    /**
     * The complete text of the .key file, with KeY strategy settings written in.
     *
     * @param strategy settings to state in the file, or null to leave KeY its own
     */
    public String run(String sourceName, String status,
            org.key_project.bench2key.run.StrategyOptions strategy) {
        List<String> antecedent = new ArrayList<>();
        List<String> succedent = new ArrayList<>();
        for (Collector.Input input : collector.inputs()) {
            String text = closed(input.formula());
            switch (input.role()) {
                case "conjecture" -> succedent.add(text);
                // Everything that is given rather than asked. TPTP says a lemma or theorem has
                // been proved from the axioms already, so it may be used like one.
                case "axiom", "hypothesis", "definition", "assumption", "lemma", "theorem",
                        "corollary", "negated_conjecture" ->
                    antecedent.add(text);
                // "plain" has no stated meaning and does not occur in the problem library, so
                // reading it as an axiom would be a guess that changes what is being proved.
                default -> throw new Unsupported("formula role " + input.role());
            }
        }
        declare();

        StringBuilder out = new StringBuilder();
        out.append("// Generated by tptp2key from ").append(sourceName).append('\n');
        out.append("// TPTP ").append(collector.language());
        if (status != null) {
            out.append(", declared status ").append(status);
        }
        out.append('\n');
        if (!collector.included().isEmpty()) {
            out.append("// Includes: ").append(collector.included().size())
                .append(" file(s), the first being ").append(collector.included().get(0).getFileName())
                .append('\n');
        }
        out.append(succedent.isEmpty()
                ? "// No conjecture: a closed proof means the formulas are unsatisfiable.\n"
                : "// A closed proof means the conjecture follows from the axioms.\n");
        out.append('\n');

        // The settings block has to come before any declaration.
        if (strategy != null) {
            out.append(strategy.toKeyBlock());
        }

        if (!sorts.isEmpty()) {
            out.append("\\sorts {\n");
            sorts.forEach(s -> out.append("    ").append(s).append(";\n"));
            out.append("}\n\n");
        }
        if (!funDecls.isEmpty() || !uniqueDecls.isEmpty()) {
            out.append("\\functions {\n");
            uniqueDecls.values().forEach(d -> out.append("    ").append(d).append('\n'));
            funDecls.values().forEach(d -> out.append("    ").append(d).append('\n'));
            out.append("}\n\n");
        }
        if (!predDecls.isEmpty()) {
            out.append("\\predicates {\n");
            predDecls.values().forEach(d -> out.append("    ").append(d).append('\n'));
            out.append("}\n\n");
        }

        out.append("\\problem {\n");
        for (int i = 0; i < antecedent.size(); i++) {
            out.append("    ").append(antecedent.get(i));
            out.append(i + 1 < antecedent.size() ? ",\n" : "\n");
        }
        out.append("==>\n");
        // Several formulas in a succedent read as their disjunction, while TPTP asks for every
        // conjecture, so more than one is joined into a conjunction instead.
        out.append("    ").append(succedent.isEmpty() ? "false" : String.join("\n  & ", succedent));
        out.append("\n}\n");
        return out.toString();
    }

    /** Writes a declaration for every symbol the problem uses. */
    private void declare() {
        for (Map.Entry<String, Ast.Signature> entry : signatures.entrySet()) {
            String name = names.fun(entry.getKey());
            Ast.Signature signature = entry.getValue();
            StringBuilder args = new StringBuilder();
            for (int i = 0; i < signature.arity(); i++) {
                args.append(i == 0 ? "(" : ", ").append(sort(signature.argTypes().get(i)));
            }
            if (signature.arity() > 0) {
                args.append(")");
            }
            if (signature.isPredicate()) {
                predDecls.put(entry.getKey(), name + args + ";");
            } else {
                funDecls.put(entry.getKey(),
                    sort(signature.result()) + " " + name + args + ";");
            }
        }
    }

    /** A formula with its free variables universally quantified, as CNF clauses need. */
    private String closed(Ast.Expr expr) {
        Set<String> free = new LinkedHashSet<>();
        freeVars(expr, new LinkedHashSet<>(), free);
        Map<String, Bound> env = new HashMap<>();
        StringBuilder prefix = new StringBuilder();
        for (String var : free) {
            Bound bound = new Bound(names.freshVar(), Ast.Type.INDIVIDUAL);
            env.put(var, bound);
            sort(Ast.Type.INDIVIDUAL);
            prefix.append("\\forall ").append(INDIVIDUAL).append(' ').append(bound.name())
                .append("; (");
        }
        String body = formula(expr, env);
        return prefix + body + ")".repeat(free.size());
    }

    private void freeVars(Ast.Expr expr, Set<String> bound, Set<String> out) {
        switch (expr) {
            case Ast.Var v -> {
                if (!bound.contains(v.name())) {
                    out.add(v.name());
                }
            }
            case Ast.App app -> app.args().forEach(a -> freeVars(a, bound, out));
            case Ast.Not not -> freeVars(not.body(), bound, out);
            case Ast.Binary binary -> {
                freeVars(binary.left(), bound, out);
                freeVars(binary.right(), bound, out);
            }
            case Ast.Infix infix -> {
                freeVars(infix.left(), bound, out);
                freeVars(infix.right(), bound, out);
            }
            case Ast.Quant quant -> {
                Set<String> inner = new LinkedHashSet<>(bound);
                quant.vars().forEach(v -> inner.add(v.name()));
                freeVars(quant.body(), inner, out);
            }
            case Ast.Num n -> { }
            case Ast.Distinct d -> { }
        }
    }

    private String formula(Ast.Expr expr, Map<String, Bound> env) {
        return switch (expr) {
            case Ast.Not not -> "!(" + formula(not.body(), env) + ")";
            case Ast.Binary binary -> binary(binary, env);
            case Ast.Quant quant -> quantified(quant, env);
            case Ast.Infix infix -> equality(infix, env);
            case Ast.App app -> atom(app, env);
            case Ast.Var v -> throw new Unsupported("a variable standing for a formula");
            case Ast.Num n -> throw new Unsupported("a number standing for a formula");
            case Ast.Distinct d -> throw new Unsupported("a distinct object standing for a formula");
        };
    }

    private String binary(Ast.Binary binary, Map<String, Bound> env) {
        String left = formula(binary.left(), env);
        String right = formula(binary.right(), env);
        return switch (binary.op()) {
            case "&" -> "(" + left + " & " + right + ")";
            case "|" -> "(" + left + " | " + right + ")";
            case "=>" -> "(" + left + " -> " + right + ")";
            case "<=" -> "(" + right + " -> " + left + ")";
            case "<=>" -> "(" + left + " <-> " + right + ")";
            case "<~>" -> "!(" + left + " <-> " + right + ")";
            case "~|" -> "!(" + left + " | " + right + ")";
            case "~&" -> "!(" + left + " & " + right + ")";
            default -> throw new Unsupported("connective " + binary.op());
        };
    }

    private String quantified(Ast.Quant quant, Map<String, Bound> env) {
        Map<String, Bound> inner = new HashMap<>(env);
        StringBuilder prefix = new StringBuilder();
        for (Ast.TypedVar var : quant.vars()) {
            Ast.Type type = var.type() == null ? Ast.Type.INDIVIDUAL : var.type();
            Bound bound = new Bound(names.freshVar(), type);
            inner.put(var.name(), bound);
            prefix.append(quant.universal() ? "\\forall " : "\\exists ").append(sort(type))
                .append(' ').append(bound.name()).append("; (");
        }
        return prefix + formula(quant.body(), inner) + ")".repeat(quant.vars().size());
    }

    private String equality(Ast.Infix infix, Map<String, Bound> env) {
        Ast.Type type = commonType(infix.left(), infix.right(), env);
        String equation = "(" + term(infix.left(), type, env) + " = "
            + term(infix.right(), type, env) + ")";
        return infix.op().equals("=") ? equation : "!" + equation;
    }

    /** The type both sides of an equation have. A numeral takes the type of the other side. */
    private Ast.Type commonType(Ast.Expr left, Ast.Expr right, Map<String, Bound> env) {
        Ast.Type type = typeOf(left, env);
        return type == null ? typeOf(right, env) : type;
    }

    private String atom(Ast.App app, Map<String, Bound> env) {
        if (app.kind() == Ast.Kind.DEFINED) {
            return definedAtom(app, env);
        }
        if (app.kind() == Ast.Kind.SYSTEM) {
            throw new Unsupported("the system predicate " + app.name());
        }
        Ast.Signature signature = signature(app);
        if (!signature.isPredicate()) {
            throw new Unsupported("the function " + app.name() + " used as a predicate");
        }
        return names.fun(app.name()) + arguments(app, signature, env);
    }

    /** The TPTP defined predicates: truth, the integer comparisons, and {@code $distinct}. */
    private String definedAtom(Ast.App app, Map<String, Bound> env) {
        List<Ast.Expr> args = app.args();
        switch (app.name()) {
            case "$true":
                return "true";
            case "$false":
                return "false";
            case "$less":
                return compare(args, "<", env);
            case "$lesseq":
                return compare(args, "<=", env);
            case "$greater":
                return compare(args, ">", env);
            case "$greatereq":
                return compare(args, ">=", env);
            case "$is_int":
            case "$is_rat":
                // Every integer is an integer and a rational, and integers are all this covers.
                integer(args.get(0), env);
                return "true";
            case "$distinct": {
                List<String> pairs = new ArrayList<>();
                for (int i = 0; i < args.size(); i++) {
                    for (int j = i + 1; j < args.size(); j++) {
                        Ast.Type type = commonType(args.get(i), args.get(j), env);
                        pairs.add("!(" + term(args.get(i), type, env) + " = "
                            + term(args.get(j), type, env) + ")");
                    }
                }
                return pairs.isEmpty() ? "true" : "(" + String.join(" & ", pairs) + ")";
            }
            default:
                throw new Unsupported("the defined predicate " + app.name());
        }
    }

    private String compare(List<Ast.Expr> args, String op, Map<String, Bound> env) {
        return "(" + integer(args.get(0), env) + " " + op + " " + integer(args.get(1), env) + ")";
    }

    private String term(Ast.Expr expr, Ast.Type expected, Map<String, Bound> env) {
        return switch (expr) {
            case Ast.Var v -> {
                Bound bound = env.get(v.name());
                if (bound == null) {
                    throw new Unsupported("the free variable " + v.name());
                }
                yield bound.name();
            }
            case Ast.Num num -> number(num, expected);
            case Ast.Distinct distinct -> distinctObject(distinct);
            case Ast.App app -> {
                if (app.kind() == Ast.Kind.DEFINED) {
                    yield definedTerm(app, env);
                }
                if (app.kind() == Ast.Kind.SYSTEM) {
                    throw new Unsupported("the system function " + app.name());
                }
                Ast.Signature signature = signature(app);
                if (signature.isPredicate()) {
                    throw new Unsupported("the predicate " + app.name() + " used as a term");
                }
                yield names.fun(app.name()) + arguments(app, signature, env);
            }
            default -> throw new Unsupported("a formula standing for a term");
        };
    }

    /** The TPTP defined functions. Only the integer ones have a counterpart in KeY. */
    private String definedTerm(Ast.App app, Map<String, Bound> env) {
        List<Ast.Expr> args = app.args();
        return switch (app.name()) {
            case "$sum" -> "(" + integer(args.get(0), env) + " + " + integer(args.get(1), env) + ")";
            case "$difference" ->
                "(" + integer(args.get(0), env) + " - " + integer(args.get(1), env) + ")";
            case "$product" ->
                "(" + integer(args.get(0), env) + " * " + integer(args.get(1), env) + ")";
            case "$uminus" -> "neg(" + integer(args.get(0), env) + ")";
            // KeY's div and mod are Euclidean, which is what the _e variants ask for.
            case "$quotient_e" ->
                "div(" + integer(args.get(0), env) + ", " + integer(args.get(1), env) + ")";
            case "$remainder_e" ->
                "mod(" + integer(args.get(0), env) + ", " + integer(args.get(1), env) + ")";
            // On integers these are all the identity.
            case "$floor", "$ceiling", "$truncate", "$round", "$to_int" -> integer(args.get(0), env);
            default -> throw new Unsupported("the defined function " + app.name());
        };
    }

    /** An argument that has to be an integer, which is the case for every arithmetic operator. */
    private String integer(Ast.Expr expr, Map<String, Bound> env) {
        Ast.Type type = typeOf(expr, env);
        if (type != null && !type.equals(Ast.Type.INTEGER)) {
            throw new Unsupported("arithmetic on " + type);
        }
        return term(expr, Ast.Type.INTEGER, env);
    }

    private String arguments(Ast.App app, Ast.Signature signature, Map<String, Bound> env) {
        if (app.args().isEmpty()) {
            return "";
        }
        List<String> parts = new ArrayList<>();
        for (int i = 0; i < app.args().size(); i++) {
            parts.add(term(app.args().get(i), signature.argTypes().get(i), env));
        }
        return "(" + String.join(", ", parts) + ")";
    }

    /**
     * A numeral. In a typed problem it is KeY's own integer literal; in an untyped one there is no
     * arithmetic to do and TPTP asks only that numerals differ from each other, which a unique
     * constant says.
     */
    private String number(Ast.Num num, Ast.Type expected) {
        if (num.kind() != Ast.NumKind.INTEGER) {
            throw new Unsupported("the " + num.kind().toString().toLowerCase() + " literal "
                + num.text());
        }
        String text = num.text().startsWith("+") ? num.text().substring(1) : num.text();
        if (numbersAreIntegers && (expected == null || expected.equals(Ast.Type.INTEGER))) {
            return text;
        }
        String name = names.distinct("number " + text);
        sort(Ast.Type.INDIVIDUAL);
        uniqueDecls.putIfAbsent(name, "\\unique " + INDIVIDUAL + " " + name + ";");
        return name;
    }

    /** A distinct object. Declaring it unique is what makes it differ from the others. */
    private String distinctObject(Ast.Distinct distinct) {
        String name = names.distinct(distinct.text());
        sort(Ast.Type.INDIVIDUAL);
        uniqueDecls.putIfAbsent(name, "\\unique " + INDIVIDUAL + " " + name + ";");
        return name;
    }

    private Ast.Signature signature(Ast.App app) {
        Ast.Signature signature = signatures.get(app.name());
        if (signature == null) {
            throw new Unsupported("the undeclared symbol " + app.name());
        }
        if (signature.arity() != app.args().size()) {
            throw new Unsupported("the symbol " + app.name() + " applied to " + app.args().size()
                + " arguments, declared with " + signature.arity());
        }
        return signature;
    }

    /** The type of a term, or null where the term takes its type from its surroundings. */
    private Ast.Type typeOf(Ast.Expr expr, Map<String, Bound> env) {
        return switch (expr) {
            case Ast.Var v -> {
                Bound bound = env.get(v.name());
                yield bound == null ? Ast.Type.INDIVIDUAL : bound.type();
            }
            case Ast.Distinct d -> Ast.Type.INDIVIDUAL;
            case Ast.Num n -> numbersAreIntegers ? Ast.Type.INTEGER : Ast.Type.INDIVIDUAL;
            case Ast.App app -> {
                if (app.kind() == Ast.Kind.DEFINED) {
                    yield app.name().equals("$true") || app.name().equals("$false")
                            ? Ast.Type.PROPOSITION
                            : Ast.Type.INTEGER;
                }
                Ast.Signature signature = signatures.get(app.name());
                yield signature == null ? null : signature.result();
            }
            default -> Ast.Type.PROPOSITION;
        };
    }

    /** The .key name of a type, recording any sort that has to be declared. */
    private String sort(Ast.Type type) {
        if (!type.args().isEmpty()) {
            throw new Unsupported("the type constructor " + type.name());
        }
        switch (type.name()) {
            case "$i":
                sorts.add(INDIVIDUAL);
                return INDIVIDUAL;
            case "$int":
                return "int";
            case "$o":
                throw new Unsupported("$o where a sort is needed");
            case "$rat":
            case "$real":
                throw new Unsupported("the type " + type.name() + ", which KeY has no rules for");
            default:
                if (type.name().startsWith("$")) {
                    throw new Unsupported("the type " + type.name());
                }
                String name = names.sort(type.name());
                sorts.add(name);
                return name;
        }
    }
}
